const SH={"Content-Security-Policy":"default-src 'self';script-src 'self' 'unsafe-inline';style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;font-src 'self' https://fonts.gstatic.com;img-src 'self' data: https:;frame-ancestors 'none'","X-Frame-Options":"DENY"};
const C=[{name:'Casey DiGennaro',role:'Founder & Chief Technician',bio:'Commercial fisherman turned AI architect.',repos:228,avatar:'\u2693'},{name:'Cocapn Fleet',role:'Open Source Community',bio:'Builders and operators from every corner.',repos:'growing',avatar:'\uD83D\uDEA2'}];
const HTML=`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Fleet Contributor Hub</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap" rel="stylesheet">
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;background:#0a0a0f;color:#e0e0e0}nav{display:flex;justify-content:space-between;align-items:center;padding:1.5rem 3rem;border-bottom:1px solid #1a1a2e}nav h1{font-size:1.2rem;font-weight:800;background:linear-gradient(135deg,#00d4ff,#7b2ff7);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.hero{text-align:center;padding:4rem 2rem}.hero h2{font-size:2.5rem;font-weight:800;margin-bottom:.5rem}.hero p{color:#888;max-width:500px;margin:auto}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:1.5rem;max-width:900px;margin:2rem auto;padding:0 2rem}.card{background:#111122;border:1px solid #1a1a2e;border-radius:12px;padding:2rem;text-align:center;transition:border-color .3s}.card:hover{border-color:#7b2ff7}.avatar{font-size:3rem;margin-bottom:1rem}.card h3{font-size:1.2rem;margin-bottom:.3rem}.role{color:#00d4ff;font-size:.85rem;margin-bottom:.5rem}.card p{color:#777;font-size:.9rem}.stats{display:flex;justify-content:center;gap:2rem;margin-top:1rem}.stat{text-align:center}.num{font-size:1.5rem;font-weight:800;color:#7b2ff7}.label{font-size:.7rem;color:#666}footer{text-align:center;padding:3rem;color:#444;font-size:.8rem;border-top:1px solid #1a1a2e;margin-top:3rem}</style></head><body>
<nav><h1>FLEET CONTRIBUTOR HUB</h1><span>cocapn.ai</span></nav>
<div class="hero"><h2>The People Behind the Fleet</h2><p>Every vessel has a captain. Meet the humans building the repo-first AI paradigm.</p></div>
<div class="cards" id="c"></div><footer>Contributor Hub &middot; Lucineer &middot; cocapn.ai</footer>
<script>document.getElementById('c').innerHTML=[{name:'Casey DiGennaro',role:'Founder & Chief Technician',bio:'Commercial fisherman turned AI architect.',repos:228,avatar:'\u2693'},{name:'Cocapn Fleet',role:'Open Source Community',bio:'Builders and operators from every corner.',repos:'growing',avatar:'\uD83D\uDEA2'}].map(function(c){return'<div class="card"><div class="avatar">'+c.avatar+'</div><h3>'+c.name+'</h3><div class="role">'+c.role+'</div><p>'+c.bio+'</p><div class="stats"><div class="stat"><div class="num">'+c.repos+'</div><div class="label">REPOS</div></div></div></div>';}).join('');</script></body></html>`;
export default{async fetch(r){const u=new URL(r.url);if(u.pathname==='/health')return new Response(JSON.stringify({status:'ok',contributors:2}),{headers:{'Content-Type':'application/json',...SH}});return new Response(HTML,{headers:{'Content-Type':'text/html;charset=UTF-8',...SH}})}};
